from datetime import datetime, timezone
from uuid import uuid4

from sqlalchemy import select
from sqlalchemy.orm import Session

from app.models.asset_state import AssetStateCurrent
from app.models.position import Position


class PositionService:
    def __init__(self, db: Session) -> None:
        self.db = db

    def _refresh_open_marks(self, rows: list[Position]) -> None:
        open_rows = [row for row in rows if row.status == "open"]
        if not open_rows:
            return
        symbols = [row.symbol for row in open_rows]
        asset_rows = list(self.db.scalars(select(AssetStateCurrent).where(AssetStateCurrent.symbol.in_(symbols))).all())
        asset_by_symbol = {row.symbol.upper(): row for row in asset_rows}
        changed = False
        for row in open_rows:
            asset = asset_by_symbol.get(row.symbol.upper())
            if not asset or asset.price is None:
                continue
            row.mark_price = float(asset.price)
            if row.entry_price is not None and row.quantity is not None:
                if row.side == "short":
                    row.unrealized_pnl = (float(row.entry_price) - float(row.mark_price)) * float(row.quantity)
                else:
                    row.unrealized_pnl = (float(row.mark_price) - float(row.entry_price)) * float(row.quantity)
            changed = True
        if changed:
            self.db.commit()
            for row in open_rows:
                self.db.refresh(row)

    def list_positions(self, limit: int = 100, status: str | None = None) -> list[Position]:
        stmt = select(Position)
        if status:
            stmt = stmt.where(Position.status == status)
        stmt = stmt.order_by(Position.opened_at.desc()).limit(limit)
        rows = list(self.db.scalars(stmt).all())
        self._refresh_open_marks(rows)
        return rows

    def get_open_position_for_candidate(self, candidate_id: str | None) -> Position | None:
        if not candidate_id:
            return None
        rows = list(self.db.scalars(select(Position).where(Position.status == "open")).all())
        for row in rows:
            meta = row.meta or {}
            if meta.get("candidate_id") == candidate_id:
                return row
        return None

    def get_open_position_for_symbol(self, symbol: str, side: str | None = None) -> Position | None:
        stmt = select(Position).where(Position.status == "open", Position.symbol == symbol.upper())
        if side:
            stmt = stmt.where(Position.side == side)
        stmt = stmt.order_by(Position.opened_at.desc()).limit(1)
        return self.db.scalars(stmt).first()

    def create_position(self, *, symbol: str, side: str, quantity: float, entry_price: float | None, mark_price: float | None, stop_price: float | None, target_price: float | None, meta: dict | None) -> Position:
        meta = meta or {}
        candidate_id = meta.get("candidate_id")

        # Idempotency guard: a candidate can be regenerated by the scanner after
        # execution. Do not create a second position for the same live candidate.
        existing = self.get_open_position_for_candidate(candidate_id)
        if existing is None:
            # SignalMaker currently tracks one active setup per symbol. This also
            # prevents duplicate positions if the candidate id is refreshed but the
            # same symbol/side is already open.
            existing = self.get_open_position_for_symbol(symbol, side=side)
        if existing is not None:
            existing.mark_price = mark_price if mark_price is not None else existing.mark_price
            existing.stop_price = stop_price if stop_price is not None else existing.stop_price
            existing.target_price = target_price if target_price is not None else existing.target_price
            existing.meta = {**(existing.meta or {}), **meta, "dedupe_refresh": True}
            self.db.commit()
            self.db.refresh(existing)
            return existing

        row = Position(position_id=f"pos_{uuid4().hex[:16]}", symbol=symbol.upper(), side=side, quantity=quantity, entry_price=entry_price, mark_price=mark_price, stop_price=stop_price, target_price=target_price, status="open", meta=meta)
        self.db.add(row)
        self.db.commit()
        self.db.refresh(row)
        return row

    def close_position(self, position_id: str, *, mark_price: float | None, unrealized_pnl: float | None = None) -> Position | None:
        row = self.db.get(Position, position_id)
        if row is None:
            return None
        row.status = "closed"
        row.mark_price = mark_price
        row.unrealized_pnl = unrealized_pnl
        row.closed_at = datetime.now(timezone.utc)
        self.db.commit()
        self.db.refresh(row)
        return row
