(function () {
  var apiBase = window.SIGNALMAKER_API_BASE || '';
  var adminSettingsPayload = null;
  var adminSettingsDirty = false;
  var adminSettingsSources = {};

  function text(value) {
    if (value === null || value === undefined || value === '') return '-';
    return String(value).replace(/[&<>'"]/g, function (c) { return {'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]; });
  }
  function setHtml(id, html) { var el = document.getElementById(id); if (el) el.innerHTML = html; }
  function operatorHeaders() { var h = { Accept: 'application/json' }; try { var k = localStorage.getItem('signalmaker_operator_key') || ''; if (k) h['x-operator-key'] = k; } catch(e) {} return h; }
  function fetchJson(path, options) { options = options || {}; var h = operatorHeaders(); if (options.body) h['Content-Type'] = 'application/json'; return fetch(apiBase + path, { method: options.method || 'GET', headers: h, body: options.body }).then(function (r) { if (!r.ok) { if (r.status === 401 || r.status === 403) throw new Error('Token admin invalide ou manquant'); throw new Error(r.status + ' ' + r.statusText); } return r.json(); }); }
  function asRows(p) { if (Array.isArray(p)) return p; if (!p) return []; if (Array.isArray(p.rows)) return p.rows; if (Array.isArray(p.candidates)) return p.candidates; if (Array.isArray(p.items)) return p.items; if (Array.isArray(p.data)) return p.data; return Object.keys(p).map(function (k) { var v = p[k] || {}; if (typeof v === 'object' && !Array.isArray(v)) { v.name = v.name || k; return v; } return { name:k, value:v }; }); }
  function table(rows, columns) { rows = rows || []; if (!rows.length) return '<p class="muted">Aucune donnée.</p>'; return '<div class="scroll"><table><thead><tr>' + columns.map(function (c) { return '<th>'+text(c.label)+'</th>'; }).join('') + '</tr></thead><tbody>' + rows.map(function (r) { return '<tr>' + columns.map(function (c) { var v = typeof c.value === 'function' ? c.value(r) : r[c.key]; return '<td>'+(c.html ? String(v) : text(v))+'</td>'; }).join('') + '</tr>'; }).join('') + '</tbody></table></div>'; }
  function badge(v) { var s=String(v); var cls = (v === true || ['ok','open','running','executed','filled','live'].indexOf(s.toLowerCase()) >= 0) ? 'ok' : (v === false || ['error','failed','stopped'].indexOf(s.toLowerCase()) >= 0 ? 'bad' : 'warn'); return '<span class="badge '+cls+'">'+text(v)+'</span>'; }
  function countBy(rows, key) { return rows.reduce(function (a, r) { var v = r[key] || '-'; a[v] = (a[v] || 0) + 1; return a; }, {}); }
  function statCards(items) { return '<div class="stats">' + items.map(function (i) { return '<div class="stat"><strong>'+text(i.value)+'</strong><span>'+text(i.label)+'</span></div>'; }).join('') + '</div>'; }
  function byHour(row) { var d = new Date(row.received_at || row.created_at || row.updated_at || Date.now()); if (isNaN(d.getTime())) return '-'; d.setMinutes(0,0,0); return d.toLocaleString(); }
  function rsi(row) { var p = row.payload || {}; var r = p.remote_candidate || p; return Number(row.rsi_1h || row.rsi || r.rsi_1h || r.entry_rsi || r.rsi || 0); }
  function momentumSignal(row) { var val = rsi(row); var status = String(row.status || '').toLowerCase(); if (status === 'open' || status === 'filled' || status === 'executed') return 'En trade'; if (val >= 45 && val <= 60) return 'À acheter (RSI 45-60)'; if (val > 70 || val < 45) return 'À vendre / éviter'; return 'Surveillance'; }
  function nav() { var cur = (location.pathname.split('/').pop() || 'index.html'); var aliases = { 'trading.html':'candidates.html', 'positions.html':'orders.html', 'settings.html':'ops.html', 'logs.html':'ops.html', 'feed.html':'index.html' }; cur = aliases[cur] || cur; var items = [['index.html','Dashboard'],['candidates.html','Trade candidates'],['orders.html','Orders / Positions'],['momentum-candidates.html','Momentum'],['ops.html','Settings / Logs']]; return items.map(function(i){ return '<a href="./'+i[0]+'"'+(cur===i[0]?' aria-current="page"':'')+'>'+i[1]+'</a>'; }).join(''); }
  function initNav(){ document.querySelectorAll('nav[data-main-nav]').forEach(function(n){ n.innerHTML = nav(); }); }

  function isAdminInput(el) { return !!(el && el.getAttribute && el.getAttribute('data-admin-section') && el.getAttribute('data-admin-key')); }
  function hasActiveEdit() { return adminSettingsDirty || isAdminInput(document.activeElement); }
  function isSecretStatus(v) { return !!(v && typeof v === 'object' && !Array.isArray(v) && Object.prototype.hasOwnProperty.call(v, 'configured')); }
  function parseAdminValue(raw, original) { if (isSecretStatus(original)) return raw ? raw : original; if (typeof original === 'boolean') return raw === 'true'; if (typeof original === 'number') { var n = Number(raw); return Number.isNaN(n) ? original : n; } if (Array.isArray(original)) return raw.split(',').map(function (x) { return x.trim(); }).filter(Boolean); return raw; }
  function inputType(key, v) { if (/(_api_key|_secret_key|telegram_secret|discord_url)$/i.test(key)) return 'password'; if (typeof v === 'number') return 'number'; if (/url|endpoint|base/i.test(key)) return 'url'; return 'text'; }
  function sourceLabel(source) { return ({'db':'DB','.env/bootstrap':'.env fallback','default':'default','legacy_migration':'legacy migration'})[source] || source || 'default'; }
  function sourceHint(section, key) { var source = adminSettingsSources[section] && adminSettingsSources[section][key]; return ' <small class="muted">'+text(sourceLabel(source))+'</small>'; }
  function renderAdminSettings(payload) { var wrapped = payload && payload.settings; adminSettingsPayload = wrapped || payload || {}; adminSettingsSources = (payload && payload.sources) || {}; var sections = Object.keys(adminSettingsPayload).sort(); return sections.map(function (section) { var vals = adminSettingsPayload[section] || {}; var rows = Object.keys(vals).sort().map(function (key) { var v = vals[key]; var hint = sourceHint(section, key); if (typeof v === 'boolean') return '<tr><td><code>'+text(key)+'</code>'+hint+'</td><td><select data-admin-section="'+text(section)+'" data-admin-key="'+text(key)+'"><option value="true"'+(v?' selected':'')+'>true</option><option value="false"'+(!v?' selected':'')+'>false</option></select></td></tr>'; if (isSecretStatus(v)) { var status = v.configured ? 'configuré' : 'non configuré'; return '<tr><td><code>'+text(key)+'</code>'+hint+'</td><td><span class="badge '+(v.configured?'ok':'warn')+'">'+status+'</span> <input type="password" autocomplete="new-password" placeholder="remplacer" data-admin-section="'+text(section)+'" data-admin-key="'+text(key)+'" value=""></td></tr>'; } var display = Array.isArray(v) ? v.join(',') : v; return '<tr><td><code>'+text(key)+'</code>'+hint+'</td><td><input type="'+inputType(key, v)+'" list="settings-suggestions" autocomplete="on" data-admin-section="'+text(section)+'" data-admin-key="'+text(key)+'" value="'+text(display)+'"></td></tr>'; }).join(''); return '<details open><summary>'+text(section)+'</summary><div class="scroll"><table><tbody>'+rows+'</tbody></table></div></details>'; }).join(''); }
  function loadOperatorToken() { var i = document.getElementById('operator-key-input'); if (!i || document.activeElement === i || i.dataset.loaded) return; try { i.value = localStorage.getItem('signalmaker_operator_key') || ''; i.dataset.loaded = 'true'; } catch(e) {} }
  function saveOperatorToken() { var i = document.getElementById('operator-key-input'); try { localStorage.setItem('signalmaker_operator_key', i.value || ''); setHtml('operator-key-result','Token local sauvegardé.'); } catch(e) { setHtml('operator-key-result','Erreur token : '+text(e.message)); } }
  function loadAdminSettings(force) { if (!document.getElementById('admin-settings-content') && !document.getElementById('device-settings-summary')) return Promise.resolve(); if (!force && hasActiveEdit()) return Promise.resolve(); return fetchJson('/api/v1/admin/settings?include_sources=true').then(function(p){ if(document.getElementById('admin-settings-content')) setHtml('admin-settings-content', renderAdminSettings(p)); renderSettingsSummary(p.settings || p); }).catch(function(e){ setHtml('admin-settings-content','<p class="warn">Réglages indisponibles : '+text(e.message)+'</p>'); setHtml('device-settings-summary','<p class="warn">Réglages indisponibles : '+text(e.message)+'</p>'); }); }
  function saveAdminSettings() { var payload = JSON.parse(JSON.stringify(adminSettingsPayload || {})); document.querySelectorAll('[data-admin-section][data-admin-key]').forEach(function (input) { var s=input.dataset.adminSection, k=input.dataset.adminKey; payload[s] = payload[s] || {}; payload[s][k] = parseAdminValue(input.value, adminSettingsPayload[s] && adminSettingsPayload[s][k]); }); return fetchJson('/api/v1/admin/settings', {method:'PUT', body:JSON.stringify(payload)}).then(function(p){ adminSettingsDirty=false; setHtml('admin-save-result','Réglages sauvegardés et relus depuis l’API.'); setHtml('admin-settings-content', renderAdminSettings(p)); renderSettingsSummary(p.settings || p); }).catch(function(e){ setHtml('admin-save-result','Erreur sauvegarde : '+text(e.message)); }); }
  function pick(obj, keys){ for(var i=0;i<keys.length;i++){ var parts=keys[i].split('.'), v=obj; for(var j=0;j<parts.length && v;j++) v=v[parts[j]]; if(v!==undefined && v!==null && v!=='') return v; } return '-'; }
  function hasPath(obj, key){ var parts=key.split('.'), v=obj; for(var i=0;i<parts.length && v;i++) v=v[parts[i]]; return v!==undefined && v!==null && v!==''; }
  function renderSettingsSummary(p){
    if(!document.getElementById('device-settings-summary')) return;
    var items = [
      {label:'SignalMaker distant',value:pick(p,['momentum.signalmaker_base_url'])},
      {label:'Exchange',value:pick(p,['executor.execution_exchange'])},
      {label:'Mode',value:pick(p,['live.live_trading_enabled'])===true?'live':'dry-run'}
    ];
    if(hasPath(p,'market_data.kraken_collector_enabled')) items.push({label:'Candle feed',value:pick(p,['market_data.kraken_collector_enabled'])});
    setHtml('device-settings-summary', statCards(items));
  }

  function loadHealth() { return fetchJson('/api/v1/health').catch(function(){return fetchJson('/healthz');}).then(function(d){ setHtml('health', badge(d.status || 'ok')+' '+text(d.service || 'SignalMaker Raspberry Executor')); }).catch(function(e){ var el=document.getElementById('health'); if(el){el.className='bad'; el.textContent='API indisponible : '+e.message;} }); }
  function loadPositions(){ return fetchJson('/api/v1/positions?limit=100').then(function(p){ var rows=asRows(p); setHtml('positions-summary', statCards([{label:'Positions',value:rows.length},{label:'Ouvertes',value:rows.filter(function(r){return r.status==='open';}).length},{label:'Executed',value:rows.filter(function(r){return r.status==='executed'||r.status==='filled';}).length}])); setHtml('positions-content', table(rows,[{key:'status',label:'Status'},{key:'symbol',label:'Symbol'},{key:'side',label:'Side'},{key:'quantity',label:'Qty'},{key:'entry_price',label:'Entry'},{key:'target_price',label:'TP'},{key:'stop_loss',label:'SL'},{key:'unrealized_pnl',label:'PnL'},{key:'opened_at',label:'Ouvert'}])); }).catch(function(e){ setHtml('positions-content','<p class="warn">Positions indisponibles : '+text(e.message)+'</p>'); }); }
  function loadCandidates(){ return fetchJson('/api/v1/trade-candidates?limit=200').then(function(p){ var rows=asRows(p); setHtml('candidates-summary', statCards([{label:'Reçus',value:rows.length},{label:'Open',value:rows.filter(function(r){return r.status==='open';}).length},{label:'Executed',value:rows.filter(function(r){return r.status==='executed'||r.status==='filled';}).length}])); setHtml('candidates-content', table(rows,[{label:'Heure reçue',value:byHour},{key:'candidate_id',label:'ID'},{key:'symbol',label:'Symbol'},{key:'stage',label:'Stage'},{key:'side',label:'Side'},{key:'entry_price',label:'Entry'},{key:'target_price',label:'TP'},{key:'stop_loss',label:'SL'},{key:'score',label:'Score'},{key:'status',label:'Status'},{key:'created_at',label:'Reçu'}])); }).catch(function(e){ setHtml('candidates-content','<p class="warn">Candidats indisponibles : '+text(e.message)+'</p>'); }); }
  function loadMomentum(){ return fetchJson('/api/v1/trade-candidates?limit=200&stage=momentum').then(function(p){ var rows=asRows(p); var groups=countBy(rows.map(function(r){ r._decision=momentumSignal(r); return r; }), '_decision'); setHtml('momentum-summary', statCards(Object.keys(groups).map(function(k){return {label:k,value:groups[k]};}))); setHtml('momentum-content', table(rows,[{label:'Décision',value:function(r){return r._decision||momentumSignal(r);}},{key:'symbol',label:'Symbol'},{key:'side',label:'Side'},{label:'RSI',value:rsi},{key:'score',label:'Score'},{key:'entry_price',label:'Entry'},{key:'target_price',label:'TP'},{key:'stop_loss',label:'SL'},{key:'status',label:'Status'},{key:'created_at',label:'Reçu'}])); }).catch(function(e){ setHtml('momentum-content','<p class="warn">Momentum indisponible : '+text(e.message)+'</p>'); }); }
  function loadAssets(){ return fetchJson('/api/v1/assets?limit=100&sort_by=updated_at').then(function(p){ var rows=asRows(p); setHtml('assets-summary', statCards([{label:'Actifs suivis',value:rows.length}])); setHtml('assets-content', table(rows,[{key:'symbol',label:'Symbol'},{key:'state',label:'State'},{key:'bias',label:'Bias'},{key:'score',label:'Score'},{key:'rsi_15m',label:'RSI 15m'},{key:'updated_at',label:'MAJ'}])); }).catch(function(e){ setHtml('assets-content','<p class="warn">Actifs indisponibles : '+text(e.message)+'</p>'); }); }
  function loadOrders(){ if(document.getElementById('orders-content')) fetchJson('/api/v1/orders?limit=100').then(function(p){ setHtml('orders-content', table(asRows(p),[{key:'order_id',label:'ID'},{key:'symbol',label:'Symbol'},{key:'side',label:'Side'},{key:'order_type',label:'Type'},{key:'quantity',label:'Qty'},{key:'status',label:'Status'},{key:'created_at',label:'Date'}])); }).catch(function(e){setHtml('orders-content','<p class="warn">Orders indisponibles : '+text(e.message)+'</p>');}); if(document.getElementById('fills-content')) fetchJson('/api/v1/fills?limit=100').then(function(p){ setHtml('fills-content', table(asRows(p),[{key:'symbol',label:'Symbol'},{key:'side',label:'Side'},{key:'quantity',label:'Qty'},{key:'price',label:'Prix'},{key:'created_at',label:'Date'}])); }).catch(function(e){setHtml('fills-content','<p class="warn">Fills indisponibles : '+text(e.message)+'</p>');}); }
  function loadFeed(){ if(document.getElementById('candles-summary')) fetchJson('/api/v1/market-data/candles/summary').then(function(p){ setHtml('candles-summary','<pre>'+text(JSON.stringify(p,null,2))+'</pre>'); }).catch(function(e){setHtml('candles-summary','<p class="warn">Résumé candles indisponible : '+text(e.message)+'</p>');}); if(document.getElementById('candles-content')) fetchJson('/api/v1/market-data/candles?limit=100&latest=true').then(function(p){ setHtml('candles-content', table(asRows(p),[{key:'symbol',label:'Symbol'},{key:'timeframe',label:'TF'},{key:'timestamp',label:'Timestamp'},{key:'open',label:'Open'},{key:'high',label:'High'},{key:'low',label:'Low'},{key:'close',label:'Close'},{key:'volume',label:'Volume'}])); }).catch(function(e){setHtml('candles-content','<p class="warn">Candles indisponibles : '+text(e.message)+'</p>');}); }
  function workerTable(rows){ return table(rows,[{key:'name',label:'Worker'},{label:'Status',value:function(r){return r.running?'running':'stopped';}},{key:'pid',label:'PID'},{label:'Actions',html:true,value:function(r){return '<button data-worker="'+text(r.name)+'" data-worker-action="start">Start</button> <button class="danger" data-worker="'+text(r.name)+'" data-worker-action="stop">Stop</button>';}}]); }
  function loadAdminWorkers(){ if(!document.getElementById('admin-workers-content') && !document.getElementById('workers-content')) return Promise.resolve(); return fetchJson('/api/v1/admin/workers').then(function(p){ var html=workerTable(asRows(p)); setHtml('admin-workers-content',html); setHtml('workers-content',html); }).catch(function(e){ setHtml('admin-workers-content','<p class="warn">Workers indisponibles : '+text(e.message)+'</p>'); setHtml('workers-content','<p class="warn">Workers indisponibles : '+text(e.message)+'</p>'); }); }
  function loadOps(){ if(document.getElementById('services-content')) fetchJson('/api/v1/services').then(function(p){ setHtml('services-content', table(asRows(p),[{key:'name',label:'Service'},{key:'status',label:'Status'},{key:'detail',label:'Détail'}])); }).catch(function(e){setHtml('services-content','<p class="warn">Services indisponibles : '+text(e.message)+'</p>');}); }
  function loadLogs(){ if(document.getElementById('logs-content')) fetchJson('/api/v1/admin/logs/executor?lines=160').then(function(p){ setHtml('logs-content','<pre>'+text((p.lines||[]).join('\n'))+'</pre>'); }).catch(function(e){ setHtml('logs-content','<p class="warn">Logs indisponibles : '+text(e.message)+'</p>'); }); }
  function loadAsset(){ var i=document.getElementById('asset-symbol'); var symbol=(i&&i.value)||new URLSearchParams(location.search).get('symbol')||''; if(i&&symbol)i.value=symbol; if(!symbol)return; fetchJson('/api/v1/assets/'+encodeURIComponent(symbol)).then(function(p){setHtml('asset-content','<pre>'+text(JSON.stringify(p,null,2))+'</pre>');}).catch(function(e){setHtml('asset-content','<p class="warn">Actif indisponible : '+text(e.message)+'</p>');}); }
  function postAdminAction(path,id){ fetchJson(path,{method:'POST'}).then(function(p){setHtml(id,'<pre>'+text(JSON.stringify(p,null,2))+'</pre>'); refresh(true);}).catch(function(e){setHtml(id,'Erreur : '+text(e.message));}); }
  function refresh(force){ var u=document.getElementById('updated-at'); if(u) u.textContent=new Date().toLocaleString(); loadOperatorToken(); if(document.getElementById('health')) loadHealth(); if(document.getElementById('positions-content')) loadPositions(); if(document.getElementById('candidates-content')) loadCandidates(); if(document.getElementById('momentum-content')) loadMomentum(); if(document.getElementById('assets-content')) loadAssets(); loadOrders(); loadFeed(); loadOps(); loadLogs(); loadAdminWorkers(); loadAdminSettings(!!force); loadAsset(); }
  initNav();
  document.addEventListener('input', function(e){ if(isAdminInput(e.target)) adminSettingsDirty=true; }); document.addEventListener('change', function(e){ if(isAdminInput(e.target)) adminSettingsDirty=true; });
  document.addEventListener('click', function(e){ var a=e.target&&e.target.getAttribute('data-action'); var wa=e.target&&e.target.getAttribute('data-worker-action'); if(a==='refresh') refresh(true); if(a==='sync-momentum') postAdminAction('/api/v1/executor/sync-momentum-candidates','sync-result'); if(a==='run-executor') postAdminAction('/api/v1/executor/run-once','executor-run-result'); if(a==='load-asset') loadAsset(); if(a==='save-operator-token') saveOperatorToken(); if(a==='save-admin-settings') saveAdminSettings(); if(a==='reset-database'&&confirm('Effacer toutes les données runtime et les logs, en gardant uniquement les settings ?')) postAdminAction('/api/v1/admin/reset-database','admin-action-result'); if(a==='test-kraken') postAdminAction('/api/v1/admin/test/kraken','admin-action-result'); if(a==='test-notifications') postAdminAction('/api/v1/admin/test/notifications','admin-action-result'); if(wa){ postAdminAction('/api/v1/admin/workers/'+e.target.getAttribute('data-worker')+'/'+wa, 'ops-action-result'); } });
  refresh(); setInterval(function(){ refresh(false); }, 30000);
}());
