ALTER TABLE momentum_current
    ADD COLUMN IF NOT EXISTS momentum_delta_15m
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_delta_1h
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_delta_4h
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_acceleration_15m
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_acceleration_1h
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_acceleration_4h
        DOUBLE PRECISION NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS momentum_acceleration
        DOUBLE PRECISION NOT NULL DEFAULT 0;
